name: Bug Report
description: Report a bug in bac-py
labels: ["bug"]
body:
  - type: textarea
    id: description
    attributes:
      label: Description
      description: A clear description of the bug.
    validations:
      required: true

  - type: textarea
    id: reproduce
    attributes:
      label: Steps to Reproduce
      description: Minimal code or steps to reproduce the issue.
      render: python
    validations:
      required: true

  - type: textarea
    id: expected
    attributes:
      label: Expected Behavior
      description: What you expected to happen.
    validations:
      required: true

  - type: textarea
    id: actual
    attributes:
      label: Actual Behavior
      description: What actually happened. Include tracebacks if applicable.
    validations:
      required: true

  - type: input
    id: version
    attributes:
      label: bac-py Version
      description: "Output of: python -c \"import bac_py; print(bac_py.__version__)\""
      placeholder: "1.4.9"
    validations:
      required: true

  - type: input
    id: python-version
    attributes:
      label: Python Version
      description: "Output of: python --version"
      placeholder: "3.13.0"
    validations:
      required: true

  - type: input
    id: os
    attributes:
      label: Operating System
      placeholder: "macOS 15, Ubuntu 24.04, Windows 11, etc."
    validations:
      required: false

  - type: textarea
    id: context
    attributes:
      label: Additional Context
      description: Any other relevant information (transport type, network setup, etc.).
    validations:
      required: false
