"""BACnet enumeration types per ASHRAE 135-2016."""

from enum import IntEnum


class ObjectType(IntEnum):
    """BACnet object types (Clause 12)."""

    ANALOG_INPUT = 0
    ANALOG_OUTPUT = 1
    ANALOG_VALUE = 2
    BINARY_INPUT = 3
    BINARY_OUTPUT = 4
    BINARY_VALUE = 5
    CALENDAR = 6
    COMMAND = 7
    DEVICE = 8
    EVENT_ENROLLMENT = 9
    FILE = 10
    GROUP = 11
    LOOP = 12
    MULTI_STATE_INPUT = 13
    MULTI_STATE_OUTPUT = 14
    NOTIFICATION_CLASS = 15
    PROGRAM = 16
    SCHEDULE = 17
    AVERAGING = 18
    MULTI_STATE_VALUE = 19
    TREND_LOG = 20
    LIFE_SAFETY_POINT = 21
    LIFE_SAFETY_ZONE = 22
    ACCUMULATOR = 23
    PULSE_CONVERTER = 24
    EVENT_LOG = 25
    GLOBAL_GROUP = 26
    TREND_LOG_MULTIPLE = 27
    LOAD_CONTROL = 28
    STRUCTURED_VIEW = 29
    ACCESS_DOOR = 30
    TIMER = 31
    ACCESS_CREDENTIAL = 32
    ACCESS_POINT = 33
    ACCESS_RIGHTS = 34
    ACCESS_USER = 35
    ACCESS_ZONE = 36
    CREDENTIAL_DATA_INPUT = 37
    NETWORK_SECURITY = 38
    BITSTRING_VALUE = 39
    CHARACTERSTRING_VALUE = 40
    DATEPATTERN_VALUE = 41
    DATE_VALUE = 42
    DATETIMEPATTERN_VALUE = 43
    DATETIME_VALUE = 44
    INTEGER_VALUE = 45
    LARGE_ANALOG_VALUE = 46
    OCTETSTRING_VALUE = 47
    POSITIVE_INTEGER_VALUE = 48
    TIMEPATTERN_VALUE = 49
    TIME_VALUE = 50
    NOTIFICATION_FORWARDER = 51
    ALERT_ENROLLMENT = 52
    CHANNEL = 53
    LIGHTING_OUTPUT = 54
    BINARY_LIGHTING_OUTPUT = 55
    NETWORK_PORT = 56
    ELEVATOR_GROUP = 57
    ESCALATOR = 58
    LIFT = 59


class PropertyIdentifier(IntEnum):
    """BACnet property identifiers (Clause 12)."""

    ACKED_TRANSITIONS = 0
    ACK_REQUIRED = 1
    ACTION = 2
    ACTION_TEXT = 3
    ACTIVE_TEXT = 4
    ACTIVE_VT_SESSIONS = 5
    ALARM_VALUE = 6
    ALARM_VALUES = 7
    ALL = 8
    ALL_WRITES_SUCCESSFUL = 9
    APDU_SEGMENT_TIMEOUT = 10
    APDU_TIMEOUT = 11
    APPLICATION_SOFTWARE_VERSION = 12
    ARCHIVE = 13
    BIAS = 14
    CHANGE_OF_STATE_COUNT = 15
    CHANGE_OF_STATE_TIME = 16
    NOTIFICATION_CLASS = 17
    CONTROLLED_VARIABLE_REFERENCE = 19
    CONTROLLED_VARIABLE_UNITS = 20
    CONTROLLED_VARIABLE_VALUE = 21
    COV_INCREMENT = 22
    DATE_LIST = 23
    DAYLIGHT_SAVINGS_STATUS = 24
    DEADBAND = 25
    DERIVATIVE_CONSTANT = 26
    DERIVATIVE_CONSTANT_UNITS = 27
    DESCRIPTION = 28
    DESCRIPTION_OF_HALT = 29
    DEVICE_ADDRESS_BINDING = 30
    DEVICE_TYPE = 31
    EFFECTIVE_PERIOD = 32
    ELAPSED_ACTIVE_TIME = 33
    ERROR_LIMIT = 34
    EVENT_ENABLE = 35
    EVENT_STATE = 36
    EVENT_TYPE = 37
    EXCEPTION_SCHEDULE = 38
    FAULT_VALUES = 39
    FEEDBACK_VALUE = 40
    FILE_ACCESS_METHOD = 41
    FILE_SIZE = 42
    FILE_TYPE = 43
    FIRMWARE_REVISION = 44
    HIGH_LIMIT = 45
    INACTIVE_TEXT = 46
    IN_PROCESS = 47
    INSTANCE_OF = 48
    INTEGRAL_CONSTANT = 49
    INTEGRAL_CONSTANT_UNITS = 50
    LIMIT_ENABLE = 52
    LIST_OF_GROUP_MEMBERS = 53
    LIST_OF_OBJECT_PROPERTY_REFERENCES = 54
    LOCAL_DATE = 56
    LOCAL_TIME = 57
    LOCATION = 58
    LOW_LIMIT = 59
    MANIPULATED_VARIABLE_REFERENCE = 60
    MAXIMUM_OUTPUT = 61
    MAX_APDU_LENGTH_ACCEPTED = 62
    MAX_INFO_FRAMES = 63
    MAX_MASTER = 64
    MAX_PRES_VALUE = 65
    MINIMUM_OFF_TIME = 66
    MINIMUM_ON_TIME = 67
    MINIMUM_OUTPUT = 68
    MIN_PRES_VALUE = 69
    MODEL_NAME = 70
    MODIFICATION_DATE = 71
    NOTIFY_TYPE = 72
    NUMBER_OF_APDU_RETRIES = 73
    NUMBER_OF_STATES = 74
    OBJECT_IDENTIFIER = 75
    OBJECT_LIST = 76
    OBJECT_NAME = 77
    OBJECT_PROPERTY_REFERENCE = 78
    OBJECT_TYPE = 79
    OPTIONAL = 80
    OUT_OF_SERVICE = 81
    OUTPUT_UNITS = 82
    EVENT_PARAMETERS = 83
    POLARITY = 84
    PRESENT_VALUE = 85
    PRIORITY = 86
    PRIORITY_ARRAY = 87
    PRIORITY_FOR_WRITING = 88
    PROCESS_IDENTIFIER = 89
    PROGRAM_CHANGE = 90
    PROGRAM_LOCATION = 91
    PROGRAM_STATE = 92
    PROPORTIONAL_CONSTANT = 93
    PROPORTIONAL_CONSTANT_UNITS = 94
    PROTOCOL_OBJECT_TYPES_SUPPORTED = 96
    PROTOCOL_SERVICES_SUPPORTED = 97
    PROTOCOL_VERSION = 98
    READ_ONLY = 99
    REASON_FOR_HALT = 100
    RECIPIENT_LIST = 102
    RELIABILITY = 103
    RELINQUISH_DEFAULT = 104
    REQUIRED = 105
    RESOLUTION = 106
    SEGMENTATION_SUPPORTED = 107
    SETPOINT = 108
    SETPOINT_REFERENCE = 109
    STATE_TEXT = 110
    STATUS_FLAGS = 111
    SYSTEM_STATUS = 112
    TIME_DELAY = 113
    TIME_OF_ACTIVE_TIME_RESET = 114
    TIME_OF_STATE_COUNT_RESET = 115
    TIME_SYNCHRONIZATION_RECIPIENTS = 116
    UNITS = 117
    UPDATE_INTERVAL = 118
    UTC_OFFSET = 119
    VENDOR_IDENTIFIER = 120
    VENDOR_NAME = 121
    VT_CLASSES_SUPPORTED = 122
    WEEKLY_SCHEDULE = 123
    ATTEMPTED_SAMPLES = 124
    AVERAGE_VALUE = 125
    BUFFER_SIZE = 126
    CLIENT_COV_INCREMENT = 127
    COV_RESUBSCRIPTION_INTERVAL = 128
    EVENT_TIME_STAMPS = 130
    LOG_BUFFER = 131
    LOG_DEVICE_OBJECT_PROPERTY = 132
    LOG_ENABLE = 133
    LOG_INTERVAL = 134
    MAXIMUM_VALUE = 135
    MINIMUM_VALUE = 136
    NOTIFICATION_THRESHOLD = 137
    PROTOCOL_REVISION = 139
    RECORDS_SINCE_NOTIFICATION = 140
    RECORD_COUNT = 141
    START_TIME = 142
    STOP_TIME = 143
    STOP_WHEN_FULL = 144
    TOTAL_RECORD_COUNT = 145
    VALID_SAMPLES = 146
    WINDOW_INTERVAL = 147
    WINDOW_SAMPLES = 148
    MAXIMUM_VALUE_TIMESTAMP = 149
    MINIMUM_VALUE_TIMESTAMP = 150
    VARIANCE_VALUE = 151
    ACTIVE_COV_SUBSCRIPTIONS = 152
    BACKUP_FAILURE_TIMEOUT = 153
    CONFIGURATION_FILES = 154
    DATABASE_REVISION = 155
    DIRECT_READING = 156
    LAST_RESTORE_TIME = 157
    MAINTENANCE_REQUIRED = 158
    MEMBER_OF = 159
    MODE = 160
    OPERATION_EXPECTED = 161
    SETTING = 162
    SILENCED = 163
    TRACKING_VALUE = 164
    ZONE_MEMBERS = 165
    LIFE_SAFETY_ALARM_VALUES = 166
    MAX_SEGMENTS_ACCEPTED = 167
    PROFILE_NAME = 168
    AUTO_SLAVE_DISCOVERY = 169
    MANUAL_SLAVE_ADDRESS_BINDING = 170
    SLAVE_ADDRESS_BINDING = 171
    SLAVE_PROXY_ENABLE = 172
    LAST_NOTIFY_RECORD = 173
    SCHEDULE_DEFAULT = 174
    ACCEPTED_MODES = 175
    ADJUST_VALUE = 176
    COUNT = 177
    COUNT_BEFORE_CHANGE = 178
    COUNT_CHANGE_TIME = 179
    COV_PERIOD = 180
    INPUT_REFERENCE = 181
    LIMIT_MONITORING_INTERVAL = 182
    LOGGING_OBJECT = 183
    LOGGING_RECORD = 184
    PRESCALE = 185
    PULSE_RATE = 186
    SCALE = 187
    SCALE_FACTOR = 188
    UPDATE_TIME = 189
    VALUE_BEFORE_CHANGE = 190
    VALUE_SET = 191
    VALUE_CHANGE_TIME = 192
    ALIGN_INTERVALS = 193
    INTERVAL_OFFSET = 195
    LAST_RESTART_REASON = 196
    LOGGING_TYPE = 197
    RESTART_NOTIFICATION_RECIPIENTS = 202
    TIME_OF_DEVICE_RESTART = 203
    TIME_DELAY_NORMAL = 204
    TIME_SYNCHRONIZATION_INTERVAL = 205
    TRIGGER = 206
    UTC_TIME_SYNCHRONIZATION_RECIPIENTS = 207
    NODE_SUBTYPE = 208
    NODE_TYPE = 209
    STRUCTURED_OBJECT_LIST = 210
    SUBORDINATE_ANNOTATIONS = 211
    SUBORDINATE_LIST = 212
    ACTUAL_SHED_LEVEL = 213
    DUTY_WINDOW = 214
    EXPECTED_SHED_LEVEL = 215
    FULL_DUTY_BASELINE = 216
    REQUESTED_SHED_LEVEL = 218
    SHED_DURATION = 219
    SHED_LEVEL_DESCRIPTIONS = 220
    SHED_LEVELS = 221
    STATE_DESCRIPTION = 222
    DOOR_ALARM_STATE = 226
    DOOR_EXTENDED_PULSE_TIME = 227
    DOOR_MEMBERS = 228
    DOOR_OPEN_TOO_LONG_TIME = 229
    DOOR_PULSE_TIME = 230
    DOOR_STATUS = 231
    DOOR_UNLOCK_DELAY_TIME = 232
    LOCK_STATUS = 233
    MASKED_ALARM_VALUES = 234
    SECURED_STATUS = 235
    ABSENTEE_LIMIT = 244
    ACCESS_ALARM_EVENTS = 245
    ACCESS_DOORS = 246
    ACCESS_EVENT = 247
    ACCESS_EVENT_AUTHENTICATION_FACTOR = 248
    ACCESS_EVENT_CREDENTIAL = 249
    ACCESS_EVENT_TIME = 250
    ACCESS_TRANSACTION_EVENTS = 251
    ACCOMPANIMENT = 252
    ACCOMPANIMENT_TIME = 253
    ACTIVATION_TIME = 254
    ACTIVE_AUTHENTICATION_POLICY = 255
    ASSIGNED_ACCESS_RIGHTS = 256
    AUTHENTICATION_FACTORS = 257
    AUTHENTICATION_POLICY_LIST = 258
    AUTHENTICATION_POLICY_NAMES = 259
    AUTHENTICATION_STATUS = 260
    AUTHORIZATION_MODE = 261
    BELONGS_TO = 262
    CREDENTIAL_DISABLE = 263
    CREDENTIAL_STATUS = 264
    CREDENTIALS = 265
    CREDENTIALS_IN_ZONE = 266
    DAYS_REMAINING = 267
    ENTRY_POINTS = 268
    EXIT_POINTS = 269
    EXPIRATION_TIME = 270
    EXTENDED_TIME_ENABLE = 271
    FAILED_ATTEMPT_EVENTS = 272
    FAILED_ATTEMPTS = 273
    FAILED_ATTEMPTS_TIME = 274
    LAST_ACCESS_EVENT = 275
    LAST_ACCESS_POINT = 276
    LAST_CREDENTIAL_ADDED = 277
    LAST_CREDENTIAL_ADDED_TIME = 278
    LAST_CREDENTIAL_REMOVED = 279
    LAST_CREDENTIAL_REMOVED_TIME = 280
    LAST_USE_TIME = 281
    LOCKOUT = 282
    LOCKOUT_RELINQUISH_TIME = 283
    MAX_FAILED_ATTEMPTS = 285
    MEMBERS = 286
    MUSTER_POINT = 287
    NEGATIVE_ACCESS_RULES = 288
    NUMBER_OF_AUTHENTICATION_POLICIES = 289
    OCCUPANCY_COUNT = 290
    OCCUPANCY_COUNT_ADJUST = 291
    OCCUPANCY_COUNT_ENABLE = 292
    OCCUPANCY_LOWER_LIMIT = 294
    OCCUPANCY_LOWER_LIMIT_ENFORCED = 295
    OCCUPANCY_STATE = 296
    OCCUPANCY_UPPER_LIMIT = 297
    OCCUPANCY_UPPER_LIMIT_ENFORCED = 298
    PASSBACK_MODE = 300
    PASSBACK_TIMEOUT = 301
    POSITIVE_ACCESS_RULES = 302
    REASON_FOR_DISABLE = 303
    SUPPORTED_FORMATS = 304
    SUPPORTED_FORMAT_CLASSES = 305
    THREAT_AUTHORITY = 306
    THREAT_LEVEL = 307
    TRACE_FLAG = 308
    TRANSACTION_NOTIFICATION_CLASS = 309
    USER_EXTERNAL_IDENTIFIER = 310
    USER_INFORMATION_REFERENCE = 311
    USER_NAME = 317
    USER_TYPE = 318
    USES_REMAINING = 319
    ZONE_FROM = 320
    ZONE_TO = 321
    ACCESS_EVENT_TAG = 322
    GLOBAL_IDENTIFIER = 323
    VERIFICATION_TIME = 326
    BASE_DEVICE_SECURITY_POLICY = 327
    DISTRIBUTION_KEY_REVISION = 328
    DO_NOT_HIDE = 329
    KEY_SETS = 330
    LAST_KEY_SERVER = 331
    NETWORK_ACCESS_SECURITY_POLICIES = 332
    PACKET_REORDER_TIME = 333
    SECURITY_PDU_TIMEOUT = 334
    SECURITY_TIME_WINDOW = 335
    SUPPORTED_SECURITY_ALGORITHMS = 336
    UPDATE_KEY_SET_TIMEOUT = 337
    BACKUP_AND_RESTORE_STATE = 338
    BACKUP_PREPARATION_TIME = 339
    RESTORE_COMPLETION_TIME = 340
    RESTORE_PREPARATION_TIME = 341
    BIT_MASK = 342
    BIT_TEXT = 343
    IS_UTC = 344
    GROUP_MEMBERS = 345
    GROUP_MEMBER_NAMES = 346
    MEMBER_STATUS_FLAGS = 347
    REQUESTED_UPDATE_INTERVAL = 348
    COVU_PERIOD = 349
    COVU_RECIPIENTS = 350
    EVENT_MESSAGE_TEXTS = 351
    EVENT_MESSAGE_TEXTS_CONFIG = 352
    EVENT_DETECTION_ENABLE = 353
    EVENT_ALGORITHM_INHIBIT = 354
    EVENT_ALGORITHM_INHIBIT_REF = 355
    TIME_DELAY_NORMAL_356 = 356
    RELIABILITY_EVALUATION_INHIBIT = 357
    FAULT_PARAMETERS = 358
    FAULT_TYPE = 359
    LOCAL_FORWARDING_ONLY = 360
    PROCESS_IDENTIFIER_FILTER = 361
    SUBSCRIBED_RECIPIENTS = 362
    PORT_FILTER = 363
    AUTHORIZATION_EXEMPTIONS = 364
    ALLOW_GROUP_DELAY_INHIBIT = 365
    CHANNEL_NUMBER = 366
    CONTROL_GROUPS = 367
    EXECUTION_DELAY = 368
    LAST_PRIORITY = 369
    WRITE_STATUS = 370
    PROPERTY_LIST = 371
    SERIAL_NUMBER = 372
    BLINK_WARN_ENABLE = 373
    DEFAULT_FADE_TIME = 374
    DEFAULT_RAMP_RATE = 375
    DEFAULT_STEP_INCREMENT = 376
    EGRESS_TIME = 377
    IN_PROGRESS = 378
    INSTANTANEOUS_POWER = 379
    LIGHTING_COMMAND = 380
    LIGHTING_COMMAND_DEFAULT_PRIORITY = 381
    MAX_ACTUAL_VALUE = 382
    MIN_ACTUAL_VALUE = 383
    POWER = 384
    TRANSITION = 385
    EGRESS_ACTIVE = 386
    CURRENT_COMMAND_PRIORITY = 431


class ErrorClass(IntEnum):
    """BACnet error classes (Clause 18.1.1)."""

    DEVICE = 0
    OBJECT = 1
    PROPERTY = 2
    RESOURCES = 3
    SECURITY = 4
    SERVICES = 5
    VT = 6
    COMMUNICATION = 7


class ErrorCode(IntEnum):
    """BACnet error codes (Clause 18, Clause 21 numerical order)."""

    OTHER = 0
    AUTHENTICATION_FAILED = 1  # removed in rev 11, kept for compat
    CONFIGURATION_IN_PROGRESS = 2
    DEVICE_BUSY = 3
    DYNAMIC_CREATION_NOT_SUPPORTED = 4
    FILE_ACCESS_DENIED = 5
    INCOMPATIBLE_SECURITY_LEVELS = 6  # removed in rev 11, kept for compat
    INCONSISTENT_PARAMETERS = 7
    INCONSISTENT_SELECTION_CRITERION = 8
    INVALID_DATA_TYPE = 9
    INVALID_FILE_ACCESS_METHOD = 10
    INVALID_FILE_START_POSITION = 11
    INVALID_OPERATOR_NAME = 12  # removed in rev 11, kept for compat
    INVALID_PARAMETER_DATA_TYPE = 13
    INVALID_TIME_STAMP = 14
    KEY_GENERATION_ERROR = 15  # removed in rev 11, kept for compat
    MISSING_REQUIRED_PARAMETER = 16
    NO_OBJECTS_OF_SPECIFIED_TYPE = 17
    NO_SPACE_FOR_OBJECT = 18
    NO_SPACE_TO_ADD_LIST_ELEMENT = 19
    NO_SPACE_TO_WRITE_PROPERTY = 20
    NO_VT_SESSIONS_AVAILABLE = 21
    PROPERTY_IS_NOT_A_LIST = 22
    OBJECT_DELETION_NOT_PERMITTED = 23
    OBJECT_IDENTIFIER_ALREADY_EXISTS = 24
    OPERATIONAL_PROBLEM = 25
    PASSWORD_FAILURE = 26
    READ_ACCESS_DENIED = 27
    SECURITY_NOT_SUPPORTED = 28  # removed in rev 11, kept for compat
    SERVICE_REQUEST_DENIED = 29
    TIMEOUT = 30
    UNKNOWN_OBJECT = 31
    UNKNOWN_PROPERTY = 32
    # 33 removed
    UNKNOWN_VT_CLASS = 34
    UNKNOWN_VT_SESSION = 35
    UNSUPPORTED_OBJECT_TYPE = 36
    VALUE_OUT_OF_RANGE = 37
    VT_SESSION_ALREADY_CLOSED = 38
    VT_SESSION_TERMINATION_FAILURE = 39
    WRITE_ACCESS_DENIED = 40
    CHARACTER_SET_NOT_SUPPORTED = 41
    INVALID_ARRAY_INDEX = 42
    COV_SUBSCRIPTION_FAILED = 43
    NOT_COV_PROPERTY = 44
    OPTIONAL_FUNCTIONALITY_NOT_SUPPORTED = 45
    INVALID_CONFIGURATION_DATA = 46
    DATATYPE_NOT_SUPPORTED = 47
    DUPLICATE_NAME = 48
    DUPLICATE_OBJECT_ID = 49
    PROPERTY_IS_NOT_AN_ARRAY = 50
    ABORT_BUFFER_OVERFLOW = 51
    ABORT_INVALID_APDU_IN_THIS_STATE = 52
    ABORT_PREEMPTED_BY_HIGHER_PRIORITY_TASK = 53
    ABORT_SEGMENTATION_NOT_SUPPORTED = 54
    ABORT_PROPRIETARY = 55
    ABORT_OTHER = 56
    INVALID_TAG = 57
    NETWORK_DOWN = 58
    REJECT_BUFFER_OVERFLOW = 59
    REJECT_INCONSISTENT_PARAMETERS = 60
    REJECT_INVALID_PARAMETER_DATA_TYPE = 61
    REJECT_INVALID_TAG = 62
    REJECT_MISSING_REQUIRED_PARAMETER = 63
    REJECT_PARAMETER_OUT_OF_RANGE = 64
    REJECT_TOO_MANY_ARGUMENTS = 65
    REJECT_UNDEFINED_ENUMERATION = 66
    REJECT_UNRECOGNIZED_SERVICE = 67
    REJECT_PROPRIETARY = 68
    REJECT_OTHER = 69
    UNKNOWN_DEVICE = 70
    UNKNOWN_ROUTE = 71
    VALUE_NOT_INITIALIZED = 72
    INVALID_EVENT_STATE = 73
    NO_ALARM_CONFIGURED = 74
    LOG_BUFFER_FULL = 75
    LOGGED_VALUE_PURGED = 76
    NO_PROPERTY_SPECIFIED = 77
    NOT_CONFIGURED_FOR_TRIGGERED_LOGGING = 78
    UNKNOWN_SUBSCRIPTION = 79
    PARAMETER_OUT_OF_RANGE = 80
    LIST_ELEMENT_NOT_FOUND = 81
    BUSY = 82
    COMMUNICATION_DISABLED = 83
    SUCCESS = 84
    ACCESS_DENIED = 85
    BAD_DESTINATION_ADDRESS = 86
    BAD_DESTINATION_DEVICE_ID = 87
    BAD_SIGNATURE = 88
    BAD_SOURCE_ADDRESS = 89
    BAD_TIMESTAMP = 90
    CANNOT_USE_KEY = 91
    CANNOT_VERIFY_MESSAGE_ID = 92
    CORRECT_KEY_REVISION = 93
    DESTINATION_DEVICE_ID_REQUIRED = 94
    DUPLICATE_MESSAGE = 95
    ENCRYPTION_NOT_CONFIGURED = 96
    ENCRYPTION_REQUIRED = 97
    INCORRECT_KEY = 98
    INVALID_KEY_DATA = 99
    KEY_UPDATE_IN_PROGRESS = 100
    MALFORMED_MESSAGE = 101
    NOT_KEY_SERVER = 102
    SECURITY_NOT_CONFIGURED = 103
    SOURCE_SECURITY_REQUIRED = 104
    TOO_MANY_KEYS = 105
    UNKNOWN_AUTHENTICATION_TYPE = 106
    UNKNOWN_KEY = 107
    UNKNOWN_KEY_REVISION = 108
    UNKNOWN_SOURCE_MESSAGE = 109
    NOT_ROUTER_TO_DNET = 110
    ROUTER_BUSY = 111
    UNKNOWN_NETWORK_MESSAGE = 112
    MESSAGE_TOO_LONG = 113
    SECURITY_ERROR = 114
    ADDRESSING_ERROR = 115
    WRITE_BDT_FAILED = 116
    READ_BDT_FAILED = 117
    REGISTER_FOREIGN_DEVICE_FAILED = 118
    READ_FDT_FAILED = 119
    DELETE_FDT_ENTRY_FAILED = 120
    DISTRIBUTE_BROADCAST_FAILED = 121
    UNKNOWN_FILE_SIZE = 122
    ABORT_APDU_TOO_LONG = 123
    ABORT_APPLICATION_EXCEEDED_REPLY_TIME = 124
    ABORT_OUT_OF_RESOURCES = 125
    ABORT_TSM_TIMEOUT = 126
    ABORT_WINDOW_SIZE_OUT_OF_RANGE = 127
    FILE_FULL = 128
    INCONSISTENT_CONFIGURATION = 129
    INCONSISTENT_OBJECT_TYPE = 130
    INTERNAL_ERROR = 131
    NOT_CONFIGURED = 132
    OUT_OF_MEMORY = 133
    VALUE_TOO_LONG = 134
    ABORT_INSUFFICIENT_SECURITY = 135
    ABORT_SECURITY_ERROR = 136
    DUPLICATE_ENTRY = 137
    INVALID_VALUE_IN_THIS_STATE = 138


class Segmentation(IntEnum):
    """BACnet segmentation support options (Clause 20.1.2.4)."""

    BOTH = 0
    TRANSMIT = 1
    RECEIVE = 2
    NONE = 3


class AbortReason(IntEnum):
    """BACnet abort reasons (Clause 20.1.8)."""

    OTHER = 0
    BUFFER_OVERFLOW = 1
    INVALID_APDU_IN_THIS_STATE = 2
    PREEMPTED_BY_HIGHER_PRIORITY_TASK = 3
    SEGMENTATION_NOT_SUPPORTED = 4
    SECURITY_ERROR = 5
    INSUFFICIENT_SECURITY = 6
    WINDOW_SIZE_OUT_OF_RANGE = 7
    APPLICATION_EXCEEDED_REPLY_TIME = 8
    OUT_OF_RESOURCES = 9
    TSM_TIMEOUT = 10
    APDU_TOO_LONG = 11


class RejectReason(IntEnum):
    """BACnet reject reasons (Clause 20.1.7)."""

    OTHER = 0
    BUFFER_OVERFLOW = 1
    INCONSISTENT_PARAMETERS = 2
    INVALID_PARAMETER_DATA_TYPE = 3
    INVALID_TAG = 4
    MISSING_REQUIRED_PARAMETER = 5
    PARAMETER_OUT_OF_RANGE = 6
    TOO_MANY_ARGUMENTS = 7
    UNDEFINED_ENUMERATION = 8
    UNRECOGNIZED_SERVICE = 9


class PduType(IntEnum):
    """APDU PDU type identifiers (Clause 20.1)."""

    CONFIRMED_REQUEST = 0
    UNCONFIRMED_REQUEST = 1
    SIMPLE_ACK = 2
    COMPLEX_ACK = 3
    SEGMENT_ACK = 4
    ERROR = 5
    REJECT = 6
    ABORT = 7


class ConfirmedServiceChoice(IntEnum):
    """Confirmed service request types (Clause 21)."""

    ACKNOWLEDGE_ALARM = 0
    CONFIRMED_COV_NOTIFICATION = 1
    CONFIRMED_EVENT_NOTIFICATION = 2
    GET_ALARM_SUMMARY = 3
    GET_ENROLLMENT_SUMMARY = 4
    SUBSCRIBE_COV = 5
    ATOMIC_READ_FILE = 6
    ATOMIC_WRITE_FILE = 7
    ADD_LIST_ELEMENT = 8
    REMOVE_LIST_ELEMENT = 9
    CREATE_OBJECT = 10
    DELETE_OBJECT = 11
    READ_PROPERTY = 12
    READ_PROPERTY_MULTIPLE = 14
    WRITE_PROPERTY = 15
    WRITE_PROPERTY_MULTIPLE = 16
    DEVICE_COMMUNICATION_CONTROL = 17
    CONFIRMED_PRIVATE_TRANSFER = 18
    CONFIRMED_TEXT_MESSAGE = 19
    REINITIALIZE_DEVICE = 20
    VT_OPEN = 21
    VT_CLOSE = 22
    VT_DATA = 23
    READ_RANGE = 26
    LIFE_SAFETY_OPERATION = 27
    SUBSCRIBE_COV_PROPERTY = 28
    GET_EVENT_INFORMATION = 29
    SUBSCRIBE_COV_PROPERTY_MULTIPLE = 30
    CONFIRMED_COV_NOTIFICATION_MULTIPLE = 31


class UnconfirmedServiceChoice(IntEnum):
    """Unconfirmed service request types (Clause 21)."""

    I_AM = 0
    I_HAVE = 1
    UNCONFIRMED_COV_NOTIFICATION = 2
    UNCONFIRMED_EVENT_NOTIFICATION = 3
    UNCONFIRMED_PRIVATE_TRANSFER = 4
    UNCONFIRMED_TEXT_MESSAGE = 5
    TIME_SYNCHRONIZATION = 6
    WHO_HAS = 7
    WHO_IS = 8
    UTC_TIME_SYNCHRONIZATION = 9
    WRITE_GROUP = 10
    UNCONFIRMED_COV_NOTIFICATION_MULTIPLE = 11


class NetworkPriority(IntEnum):
    """NPDU network priority levels (Clause 6.2.2)."""

    NORMAL = 0
    URGENT = 1
    CRITICAL_EQUIPMENT = 2
    LIFE_SAFETY = 3


class NetworkMessageType(IntEnum):
    """Network layer message types (Clause 6.2.4)."""

    WHO_IS_ROUTER_TO_NETWORK = 0x00
    I_AM_ROUTER_TO_NETWORK = 0x01
    I_COULD_BE_ROUTER_TO_NETWORK = 0x02
    REJECT_MESSAGE_TO_NETWORK = 0x03
    ROUTER_BUSY_TO_NETWORK = 0x04
    ROUTER_AVAILABLE_TO_NETWORK = 0x05
    INITIALIZE_ROUTING_TABLE = 0x06
    INITIALIZE_ROUTING_TABLE_ACK = 0x07
    ESTABLISH_CONNECTION_TO_NETWORK = 0x08
    DISCONNECT_CONNECTION_TO_NETWORK = 0x09
    CHALLENGE_REQUEST = 0x0A
    SECURITY_PAYLOAD = 0x0B
    SECURITY_RESPONSE = 0x0C
    REQUEST_KEY_UPDATE = 0x0D
    UPDATE_KEY_SET = 0x0E
    UPDATE_DISTRIBUTION_KEY = 0x0F
    REQUEST_MASTER_KEY = 0x10
    SET_MASTER_KEY = 0x11
    WHAT_IS_NETWORK_NUMBER = 0x12
    NETWORK_NUMBER_IS = 0x13


class BvlcFunction(IntEnum):
    """BVLC function codes (Annex J)."""

    BVLC_RESULT = 0x00
    WRITE_BROADCAST_DISTRIBUTION_TABLE = 0x01
    READ_BROADCAST_DISTRIBUTION_TABLE = 0x02
    READ_BROADCAST_DISTRIBUTION_TABLE_ACK = 0x03
    FORWARDED_NPDU = 0x04
    REGISTER_FOREIGN_DEVICE = 0x05
    READ_FOREIGN_DEVICE_TABLE = 0x06
    READ_FOREIGN_DEVICE_TABLE_ACK = 0x07
    DELETE_FOREIGN_DEVICE_TABLE_ENTRY = 0x08
    DISTRIBUTE_BROADCAST_TO_NETWORK = 0x09
    ORIGINAL_UNICAST_NPDU = 0x0A
    ORIGINAL_BROADCAST_NPDU = 0x0B
    SECURE_BVLL = 0x0C


class BvlcResultCode(IntEnum):
    """BVLC-Result codes (Annex J.2)."""

    SUCCESSFUL_COMPLETION = 0x0000
    WRITE_BROADCAST_DISTRIBUTION_TABLE_NAK = 0x0010
    READ_BROADCAST_DISTRIBUTION_TABLE_NAK = 0x0020
    REGISTER_FOREIGN_DEVICE_NAK = 0x0030
    READ_FOREIGN_DEVICE_TABLE_NAK = 0x0040
    DELETE_FOREIGN_DEVICE_TABLE_ENTRY_NAK = 0x0050
    DISTRIBUTE_BROADCAST_TO_NETWORK_NAK = 0x0060


class EventState(IntEnum):
    """BACnet event state enumeration (Clause 12)."""

    NORMAL = 0
    FAULT = 1
    OFFNORMAL = 2
    HIGH_LIMIT = 3
    LOW_LIMIT = 4
    LIFE_SAFETY_ALARM = 5


class BinaryPV(IntEnum):
    """BACnet binary present value enumeration (Clause 21)."""

    INACTIVE = 0
    ACTIVE = 1


class Polarity(IntEnum):
    """BACnet polarity enumeration (Clause 12)."""

    NORMAL = 0
    REVERSE = 1


class Reliability(IntEnum):
    """BACnet reliability enumeration (Clause 12)."""

    NO_FAULT_DETECTED = 0
    NO_SENSOR = 1
    OVER_RANGE = 2
    UNDER_RANGE = 3
    OPEN_LOOP = 4
    SHORTED_LOOP = 5
    NO_OUTPUT = 6
    UNRELIABLE_OTHER = 7
    PROCESS_ERROR = 8
    MULTI_STATE_FAULT = 9
    CONFIGURATION_ERROR = 10
    COMMUNICATION_FAILURE = 12
    MEMBER_FAULT = 13
    MONITORED_OBJECT_FAULT = 14
    TRIPPED = 15
    LAMP_FAILURE = 16
    ACTIVATION_FAILURE = 17
    RENEW_DHCP_FAILURE = 18
    RENEW_FD_REGISTRATION_FAILURE = 19
    RESTART_AUTO_NEGOTIATION_FAILURE = 20
    RESTART_FAILURE = 21
    PROPRIETARY_COMMAND_FAILURE = 22
    FAULTS_LISTED = 23
    REFERENCED_OBJECT_FAULT = 24


class EngineeringUnits(IntEnum):
    """BACnet engineering units enumeration (Clause 21).

    Only commonly used units are listed; vendor-specific units
    can be represented by integer values outside this enum.
    """

    # Temperature
    DEGREES_CELSIUS = 62
    DEGREES_FAHRENHEIT = 64
    DEGREES_KELVIN = 63

    # Pressure
    PASCALS = 53
    KILOPASCALS = 54
    BARS = 55
    POUNDS_PER_SQUARE_INCH = 56
    MILLIMETERS_OF_WATER = 206
    INCHES_OF_WATER = 205

    # Flow
    CUBIC_METERS_PER_SECOND = 142
    CUBIC_METERS_PER_HOUR = 135
    LITERS_PER_SECOND = 85
    LITERS_PER_MINUTE = 88
    CUBIC_FEET_PER_MINUTE = 84
    US_GALLONS_PER_MINUTE = 89

    # Energy
    JOULES = 16
    KILOJOULES = 17
    WATT_HOURS = 18
    KILOWATT_HOURS = 19
    BTUS = 20
    THERMS = 21

    # Power
    WATTS = 48
    KILOWATTS = 49
    MEGAWATTS = 50
    HORSEPOWER = 51

    # Electrical
    VOLTS = 5
    MILLIVOLTS = 124
    AMPERES = 3
    MILLIAMPERES = 125
    OHMS = 4
    KILOHMS = 122
    MEGOHMS = 123

    # Frequency
    HERTZ = 27
    KILOHERTZ = 129
    MEGAHERTZ = 130

    # Humidity
    PERCENT_RELATIVE_HUMIDITY = 29
    PERCENT = 98

    # Length
    METERS = 31
    CENTIMETERS = 118
    MILLIMETERS = 30
    INCHES = 32
    FEET = 33

    # Time
    SECONDS = 73
    MINUTES = 72
    HOURS = 71
    DAYS = 70

    # Velocity
    METERS_PER_SECOND = 40
    FEET_PER_MINUTE = 74

    # Volume
    CUBIC_METERS = 46
    CUBIC_FEET = 79
    LITERS = 75
    US_GALLONS = 83

    # Mass
    KILOGRAMS = 28
    POUNDS_MASS = 115

    # Area
    SQUARE_METERS = 0
    SQUARE_FEET = 1

    # Concentration
    PARTS_PER_MILLION = 96

    # Illuminance
    LUX = 37

    # Special
    NO_UNITS = 95
    REVOLUTIONS_PER_MINUTE = 104
    DEGREES_ANGULAR = 90
    DEGREES_PHASE = 14


class EnableDisable(IntEnum):
    """BACnetEnableDisable values (Clause 16.4)."""

    ENABLE = 0
    DISABLE = 1
    DISABLE_INITIATION = 2


class ReinitializedState(IntEnum):
    """BACnetReinitializedStateOfDevice values (Clause 16.5)."""

    COLDSTART = 0
    WARMSTART = 1
    START_BACKUP = 2
    END_BACKUP = 3
    START_RESTORE = 4
    END_RESTORE = 5
    ABORT_RESTORE = 6
    ACTIVATE_CHANGES = 7


class FileAccessMethod(IntEnum):
    """BACnetFileAccessMethod values (Clause 12.12)."""

    STREAM_ACCESS = 0
    RECORD_ACCESS = 1
